image: python:3.8-buster

before_script:
  - pip install --upgrade pip && pip install .[dev]

pages:
  stage: deploy
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
    - public
  only:
  - optimized  # branch