site_name: QOptCraft documentation
site_description: "A package for the design and study of linear optical quantum systems."
site_url: https://namespace.gitlab.io
site_dir: public

repo_url: https://gitlab.tel.uva.es/juagar/qoptcraft
repo_name: juagar/qoptcraft
docs_dir: ./
watch: [../README.md, ../qoptcraft]

nav:
  - Introduction: index.md
  - API documentation: reference/  # defer documentation to the gen-files and literate-nav plugins

theme:
  features:
    - navigation.tracking
    - toc.follow
    - navigation.top
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "red"
      accent: "indigo"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "indigo"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - search
  - same-dir
  - autorefs
  - gen-files:
      scripts:
      - scripts/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.txt
  - section-index
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://installer.readthedocs.io/en/stable/objects.inv  # demonstration purpose in the docs
          - https://mkdocstrings.github.io/autorefs/objects.inv
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            show_submodules: no
  - mkdocs-jupyter:
      execute: false
      include_source: true
      ignore_h1_titles: True
      theme: dark

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.magiclink
  - mdx_math
